/*
 * REST API
 * Rockset's REST API allows for creating and managing all resources in Rockset. Each supported endpoint is documented below.  All requests must be authorized with a Rockset API key, which can be created in the [Rockset console](https://console.rockset.com). The API key must be provided as `ApiKey <api_key>` in the `Authorization` request header. For example: ``` Authorization: ApiKey aB35kDjg93J5nsf4GjwMeErAVd832F7ad4vhsW1S02kfZiab42sTsfW5Sxt25asT ```  All endpoints are only accessible via https.  Build something awesome!
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rockset.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Describes details about an error
 */
@ApiModel(description = "Describes details about an error")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-06T00:47:37.549Z")
public class ErrorModel {
  @SerializedName("message")
  private String message = null;

  /**
   * category of the error
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    AUTHEXCEPTION("AUTHEXCEPTION"),
    
    VERSIONEXCEPTION("VERSIONEXCEPTION"),
    
    INTERNALERROR("INTERNALERROR"),
    
    INVALIDINPUT("INVALIDINPUT"),
    
    NOTIMPLEMENTEDYET("NOTIMPLEMENTEDYET"),
    
    PROTOCOLERROR("PROTOCOLERROR"),
    
    RESOURCEEXCEEDED("RESOURCEEXCEEDED"),
    
    RESOURCENAMETOOLONG("RESOURCENAMETOOLONG"),
    
    ALREADYEXISTS("ALREADYEXISTS"),
    
    NOTFOUND("NOTFOUND"),
    
    DEPENDENTRESOURCES("DEPENDENTRESOURCES"),
    
    QUERY_ERROR("QUERY_ERROR"),
    
    NOT_READY("NOT_READY"),
    
    FORBIDDEN("FORBIDDEN"),
    
    QUERY_TIMEOUT("QUERY_TIMEOUT");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("line")
  private Integer line = null;

  @SerializedName("column")
  private Integer column = null;

  @SerializedName("trace_id")
  private String traceId = null;

  public ErrorModel message(String message) {
    this.message = message;
    return this;
  }

   /**
   * descriptive message about the error
   * @return message
  **/
  @ApiModelProperty(example = "collection not found", value = "descriptive message about the error")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ErrorModel type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * category of the error
   * @return type
  **/
  @ApiModelProperty(example = "InvalidInput", value = "category of the error")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public ErrorModel line(Integer line) {
    this.line = line;
    return this;
  }

   /**
   * Line where the error happened (if applicable)
   * @return line
  **/
  @ApiModelProperty(value = "Line where the error happened (if applicable)")
  public Integer getLine() {
    return line;
  }

  public void setLine(Integer line) {
    this.line = line;
  }

  public ErrorModel column(Integer column) {
    this.column = column;
    return this;
  }

   /**
   * Column where the error happened (if applicable)
   * @return column
  **/
  @ApiModelProperty(value = "Column where the error happened (if applicable)")
  public Integer getColumn() {
    return column;
  }

  public void setColumn(Integer column) {
    this.column = column;
  }

  public ErrorModel traceId(String traceId) {
    this.traceId = traceId;
    return this;
  }

   /**
   * Internal trace ID to help with debugging
   * @return traceId
  **/
  @ApiModelProperty(value = "Internal trace ID to help with debugging")
  public String getTraceId() {
    return traceId;
  }

  public void setTraceId(String traceId) {
    this.traceId = traceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorModel errorModel = (ErrorModel) o;
    return Objects.equals(this.message, errorModel.message) &&
        Objects.equals(this.type, errorModel.type) &&
        Objects.equals(this.line, errorModel.line) &&
        Objects.equals(this.column, errorModel.column) &&
        Objects.equals(this.traceId, errorModel.traceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, type, line, column, traceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorModel {\n");
    
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    line: ").append(toIndentedString(line)).append("\n");
    sb.append("    column: ").append(toIndentedString(column)).append("\n");
    sb.append("    traceId: ").append(toIndentedString(traceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

