/*
 * REST API
 * Rockset's REST API allows for creating and managing all resources in Rockset. Each supported endpoint is documented below.  All requests must be authorized with a Rockset API key, which can be created in the [Rockset console](https://console.rockset.com). The API key must be provided as `ApiKey <api_key>` in the `Authorization` request header. For example: ``` Authorization: ApiKey aB35kDjg93J5nsf4GjwMeErAVd832F7ad4vhsW1S02kfZiab42sTsfW5Sxt25asT ```  All endpoints are only accessible via https.  Build something awesome!
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.rockset.client.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** ValidateExpressionRequest */
@javax.annotation.Generated(
    value = "io.swagger.codegen.languages.JavaClientCodegen",
    date = "2022-04-15T10:38:36.284-04:00")
public class ValidateExpressionRequest {
  @SerializedName("sql_expression")
  private String sqlExpression = null;

  public ValidateExpressionRequest sqlExpression(String sqlExpression) {
    this.sqlExpression = sqlExpression;
    return this;
  }

  /**
   * SQL expression to be validated
   *
   * @return sqlExpression
   */
  @JsonProperty("sql_expression")
  @ApiModelProperty(example = "CAST(:field as int)", value = "SQL expression to be validated")
  public String getSqlExpression() {
    return sqlExpression;
  }

  public void setSqlExpression(String sqlExpression) {
    this.sqlExpression = sqlExpression;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidateExpressionRequest validateExpressionRequest = (ValidateExpressionRequest) o;
    return Objects.equals(this.sqlExpression, validateExpressionRequest.sqlExpression);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sqlExpression);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidateExpressionRequest {\n");

    sb.append("    sqlExpression: ").append(toIndentedString(sqlExpression)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
